# Generated by Django 2.1.5 on 2019-02-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gettagcode',
            old_name='Date',
            new_name='Labels',
        ),
        migrations.RemoveField(
            model_name='gettagcode',
            name='current_value',
        ),
    ]
