# Generated by Django 2.1.5 on 2019-02-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190211_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetTagCode',
        ),
    ]
