# Generated by Django 2.1.5 on 2019-02-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0003_delete_gettagcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetTagCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagCode', models.CharField(max_length=10)),
                ('Labels', models.CharField(max_length=10)),
            ],
        ),
    ]
