# Generated by Django 2.1.5 on 2019-02-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_gettagcode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gettagcode',
            table='final',
        ),
    ]
