# Generated by Django 2.1.5 on 2019-02-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190212_1521'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gettagcode',
            index=models.Index(fields=['TagCode', 'Labels'], name='final_TagCode_66bd77_idx'),
        ),
    ]
