# Generated by Django 2.1.5 on 2019-02-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190212_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gettagcode',
            name='Labels',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gettagcode',
            name='TagCode',
            field=models.IntegerField(max_length=10),
        ),
    ]
