# Generated by Django 2.1.5 on 2019-02-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20190212_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gettagcode',
            name='Labels',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gettagcode',
            name='TagCode',
            field=models.CharField(max_length=20),
        ),
    ]
