# Generated by Django 2.1.5 on 2019-02-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20190221_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagCode', models.CharField(max_length=20)),
                ('CurrentValue', models.CharField(max_length=20)),
                ('MinValue', models.CharField(max_length=20)),
                ('MaxValue', models.CharField(max_length=20)),
                ('MinTime', models.CharField(max_length=20)),
                ('MaxTime', models.CharField(max_length=20)),
                ('HourTime', models.CharField(max_length=20)),
            ],
        ),
    ]
