# Generated by Django 2.1.5 on 2019-02-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_report'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='report',
        ),
    ]
